### PR TITLE
FIX #27, pidusage.stat not a function

### LINKED ISSUE #27: pidusage.stat pidusage.stat is not a function
Hi,
Thank you for this great tool 👍 
I was testing the current master commit
The current commit: 1ddc160b337eb0c9e9daf1f00b726aa095bfc1f7
```
"hapijs-status-monitor": {
      "version": "git+https://github.com/ziyasal/hapijs-status-monitor.git#1ddc160b337eb0c9e9daf1f00b726aa095bfc1f7",
      "requires": {
        "pidusage": "2.0.6",
        "socket.io": "2.1.0"
      }
},
```
And it looks like it fails on:

```
/node_modules/hapijs-status-monitor/src/helpers/gather-os-metrics.js:16
  pidusage.stat(process.pid, (err, stat) => {
           ^
TypeError: pidusage.stat is not a function
    at module.exports (/Users/wessel/Development/VitalTracker/reporting-services/node_modules/hapijs-status-monitor/src/helpers/gather-os-metrics.js:16:12)
    at Timeout.setInterval [as _onTimeout] (/Users/wessel/Development/VitalTracker/reporting-services/node_modules/hapijs-status-monitor/src/helpers/socket-io-init.js:24:42)
    at ontimeout (timers.js:458:11)
    at Timer.unrefdHandle (timers.js:570:5)

```
I think it's a code breaking change in the pidusage from 1.x to 2.x that no longer makes the pidusage.stat available, I will create a little pull RQ

Regards,

### PR DESCRIPTION
**Pull request by Wesseldr**
Fixed little code breaking changes between v1.x and v2. of pidusage See issue #27

### CODE REVIEW

**Comment by danielbayerlein** [comment]
Thank you! Can you please change the test as well?

```diff
diff --git a/__tests__/helpers/gather-os-metrics.spec.js b/__tests__/helpers/gather-os-metrics.spec.js
index e8cfe23..61c942d 100755
--- a/__tests__/helpers/gather-os-metrics.spec.js
+++ b/__tests__/helpers/gather-os-metrics.spec.js
@@ -1,16 +1,15 @@
 const gatherOsMetrics = require('../../src/helpers/gather-os-metrics');
+
+jest.mock('pidusage');
 const pidusage = require('pidusage');
 
 describe('helpers', () => {
   describe('gather-os-metrics', () => {
     describe('when invoked', () => {
-      it('then pidusage.stat should be called', () => {
-        const span = { os: [], responses: [] };
-        pidusage.stat = jest.fn();
-
-        gatherOsMetrics({}, span);
+      it('then pidusage should be called', () => {
+        gatherOsMetrics({}, { os: [], responses: [] });
 
-        expect(pidusage.stat).toHaveBeenCalled();
+        expect(pidusage).toHaveBeenCalled();
       });
     });
   });
```

**Comment by Wesseldr** [comment]
Think Travis is off-track.. running the code local works fine, probly travis is still using the old pidusage v1.x lib instead of the 2.x

**Comment by danielbayerlein** [comment]
@Wesseldr See https://github.com/ziyasal/hapijs-status-monitor/pull/28#issuecomment-377544163 😉

**Comment by Wesseldr** [comment]
Pffff :-)

**Comment by danielbayerlein** [comment]
@Wesseldr Thank you! 🎉

**Pull request merged**
